export const ks1Words = [
"ant" ,"bag","bat","bed","bee","bin","box","boy","bus","car",
"cat","cow","cup","dad","dog","ear","egg","elf","fan","far",
"fat","fig","fin","fix","fox","fun","gap","gas","gem","get",
"gig","gum","gun","hat","hen","hip","hit","hop","hot","ice",
"jam","jet","jug","kit","leg","lid","lip","log","man","map",
"mat","men","mop","mud","net","nut","pan","pen","pet","pig",
"pin","pot","rat","red","rib","rod","run","sad","sat","six",
"sun","tap","ten","tip","top","toy","van","vet","web","wig",
"win","yak","zip","zoo",

"arch","army","baby","ball","barn","bath","beach","bear","bell","belt",
"bike","bird","boat","book","boot","bowl","brat","cake","calf","camp",
"card","cart","chip","clam","club","coat","corn","crib","crow","cube",
"deer","desk","doll","door","drum","duck","farm","fish","flag","frog",
"gift","girl","goat","gold","golf","hand","hill","home","hook","horn",
"hose","kite","lamb","leaf","lion","milk","moon","nest","nose","park",
"pear","plum","pond","rain","ring","road","rock","roof","room","rose",
"sand","seed","ship","shoe","shop","sock","star","stem","swim","tent",
"tile","toad","tree","vest","wall","wind","wing","wood","worm","yard",

"apple","beach","beard","bench","berry","black","blade","bland","blink","block",
"blood","board","bread","brick","bring","brush","cabin","camel","candy","chair",
"cheek","chess","chick","child","class","clock","cloud","coast","cream","crisp",
"crown","dance","daisy","dream","dress","drink","earth","field","flame","floor",
"flour","fruit","ghost","glass","grape","grass","green","group","heart","horse",
"house","juice","knife","light","lunch","magic","metal","mouse","mouth","night",
"north","ocean","peach","plant","plate","queen","quiet","river","sheep","shell",
"shirt","skirt","sleep","smile","snake","snow","sound","spoon","sport","stack",
"stone","storm","sugar","table","teach","tiger","toast","train","truck","water",
"whale","wheel","white","woman","world","zebra"
];
